// QuantDrill Badge Definitions Part 3 (197 badges - final section)

export const BADGES_PART_3 = [
  // ── Difficulty Badges (15) ─────────────────────────────────────────
  {
    id: 'hard_1',
    label: 'Hard Mode Initiate',
    description: 'Complete 1 hard mode session',
    category: 'difficulty',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ hardCount }) => (hardCount ?? 0) >= 1,
  },
  {
    id: 'hard_5',
    label: 'Hard Mode Challenger',
    description: 'Complete 5 hard mode sessions',
    category: 'difficulty',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ hardCount }) => (hardCount ?? 0) >= 5,
  },
  {
    id: 'hard_10',
    label: 'Hard Mode Champion',
    description: 'Complete 10 hard mode sessions',
    category: 'difficulty',
    emoji: '🔥',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ hardCount }) => (hardCount ?? 0) >= 10,
  },
  {
    id: 'hard_25',
    label: 'Hard Mode Expert',
    description: 'Complete 25 hard mode sessions',
    category: 'difficulty',
    emoji: '🔥',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ hardCount }) => (hardCount ?? 0) >= 25,
  },
  {
    id: 'hard_50',
    label: 'Hard Mode Legend',
    description: 'Complete 50 hard mode sessions',
    category: 'difficulty',
    emoji: '🔥',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ hardCount }) => (hardCount ?? 0) >= 50,
  },
  {
    id: 'medium_100',
    label: 'Medium Grinder',
    description: 'Complete 100 medium mode sessions',
    category: 'difficulty',
    emoji: '⚔️',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ mediumCount }) => (mediumCount ?? 0) >= 100,
  },
  {
    id: 'medium_200',
    label: 'Medium Master',
    description: 'Complete 200 medium mode sessions',
    category: 'difficulty',
    emoji: '⚔️',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ mediumCount }) => (mediumCount ?? 0) >= 200,
  },
  {
    id: 'medium_500',
    label: 'Medium Legend',
    description: 'Complete 500 medium mode sessions',
    category: 'difficulty',
    emoji: '⚔️',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ mediumCount }) => (mediumCount ?? 0) >= 500,
  },
  {
    id: 'easy_10',
    label: 'Easy Starter',
    description: 'Complete 10 easy mode sessions',
    category: 'difficulty',
    emoji: '🎯',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ easyCount }) => (easyCount ?? 0) >= 10,
  },
  {
    id: 'easy_25',
    label: 'Easy Enthusiast',
    description: 'Complete 25 easy mode sessions',
    category: 'difficulty',
    emoji: '🎯',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ easyCount }) => (easyCount ?? 0) >= 25,
  },
  {
    id: 'easy_50',
    label: 'Easy Master',
    description: 'Complete 50 easy mode sessions',
    category: 'difficulty',
    emoji: '🎯',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ easyCount }) => (easyCount ?? 0) >= 50,
  },
  {
    id: 'first_hard',
    label: 'Courage',
    description: 'Attempt hard mode for the first time',
    category: 'difficulty',
    emoji: '💪',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ attemptedHard }) => (attemptedHard ?? false),
  },
  {
    id: 'perfect_hard',
    label: 'Hard Mode Perfect',
    description: 'Score 100% on a hard mode session',
    category: 'difficulty',
    emoji: '✨',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ perfectHard }) => (perfectHard ?? false),
  },
  {
    id: 'hard_10_streak',
    label: 'Hard Mode Streak',
    description: 'Complete 10 consecutive hard mode sessions',
    category: 'difficulty',
    emoji: '🔥',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ hardStreak10 }) => (hardStreak10 ?? false),
  },

  // ── Time of Day Badges (10) ────────────────────────────────────────
  {
    id: 'early_bird',
    label: 'Early Bird',
    description: 'Train before 7am',
    category: 'time_of_day',
    emoji: '🌅',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ trainedEarly }) => (trainedEarly ?? false),
  },
  {
    id: 'night_owl',
    label: 'Night Owl',
    description: 'Train after 10pm',
    category: 'time_of_day',
    emoji: '🦉',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ trainedLate }) => (trainedLate ?? false),
  },
  {
    id: 'dawn_warrior',
    label: 'Dawn Warrior',
    description: 'Train 7 days in a row before 8am',
    category: 'time_of_day',
    emoji: '🌅',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ earlyMorningStreak7 }) => (earlyMorningStreak7 ?? false),
  },
  {
    id: 'midnight_warrior',
    label: 'Midnight Warrior',
    description: 'Train at exactly midnight',
    category: 'time_of_day',
    emoji: '⏰',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ trainedMidnight }) => (trainedMidnight ?? false),
  },
  {
    id: 'late_night_5',
    label: 'Late Night Grinder',
    description: 'Train 5 days in a row after 9pm',
    category: 'time_of_day',
    emoji: '🦉',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ lateNightStreak5 }) => (lateNightStreak5 ?? false),
  },
  {
    id: 'morning_routine',
    label: 'Morning Routine',
    description: 'Train every morning for a week',
    category: 'time_of_day',
    emoji: '☀️',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ morningRoutine }) => (morningRoutine ?? false),
  },
  {
    id: 'time_keeper',
    label: 'Time Keeper',
    description: 'Train at the same time 7 days in a row',
    category: 'time_of_day',
    emoji: '⏰',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ sameTimeStreak7 }) => (sameTimeStreak7 ?? false),
  },
  {
    id: 'weekend_warrior',
    label: 'Weekend Warrior',
    description: 'Train both days of 4 weekends',
    category: 'time_of_day',
    emoji: '⛹️',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ weekendWarrior }) => (weekendWarrior ?? false),
  },
  {
    id: 'holiday_trainer',
    label: 'Holiday Trainer',
    description: 'Train on a holiday',
    category: 'time_of_day',
    emoji: '🎉',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ trainedHoliday }) => (trainedHoliday ?? false),
  },
  {
    id: 'birthday_trainer',
    label: 'Birthday Trainer',
    description: 'Train on your birthday',
    category: 'time_of_day',
    emoji: '🎂',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ trainedBirthday }) => (trainedBirthday ?? false),
  },

  // ── Special Milestones (22 — 3 removed as duplicates) ──────────────────────────────────────────
  {
    id: 'milestone_premium',
    label: 'Premium Access',
    description: 'Unlock premium features',
    category: 'special',
    emoji: '💎',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ isPremium }) => (isPremium ?? false),
  },
  {
    id: 'milestone_10min',
    label: '10-Minute Challenge',
    description: 'Complete a 10-minute session',
    category: 'special',
    emoji: '⏱️',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ completed10min }) => (completed10min ?? false),
  },
  {
    id: 'milestone_2min',
    label: '2-Minute Flash',
    description: 'Complete a 2-minute session',
    category: 'special',
    emoji: '⚡',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ completed2min }) => (completed2min ?? false),
  },
  {
    id: 'milestone_3consecutive',
    label: 'Momentum Builder',
    description: 'Improve score 3 sessions in a row',
    category: 'special',
    emoji: '📈',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ improvement3 }) => (improvement3 ?? false),
  },
  {
    id: 'milestone_best_5',
    label: 'Personal Best Hunter',
    description: 'Beat personal best 5 times',
    category: 'special',
    emoji: '🏆',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ bestBeaten5 }) => (bestBeaten5 ?? false),
  },
  {
    id: 'milestone_month_perfect',
    label: 'Consistent Month',
    description: 'Trained every day for a month',
    category: 'special',
    emoji: '📅',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ monthPerfect }) => (monthPerfect ?? false),
  },
  {
    id: 'milestone_500correct',
    label: '500 Correct Answers',
    description: '500 total correct answers',
    category: 'special',
    emoji: '✓',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ correctAnswers500 }) => (correctAnswers500 ?? false),
  },
  {
    id: 'milestone_1000correct',
    label: '1000 Correct Answers',
    description: '1000 total correct answers',
    category: 'special',
    emoji: '✓',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ correctAnswers1000 }) => (correctAnswers1000 ?? false),
  },
  {
    id: 'milestone_5000correct',
    label: '5000 Correct Answers',
    description: '5000 total correct answers',
    category: 'special',
    emoji: '✓',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ correctAnswers5000 }) => (correctAnswers5000 ?? false),
  },
  {
    id: 'milestone_100under5s',
    label: 'Speed Burst',
    description: '100 questions answered under 5 seconds',
    category: 'special',
    emoji: '⚡',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ under5sCount100 }) => (under5sCount100 ?? false),
  },
  {
    id: 'milestone_percentile',
    label: 'Elite Percentile',
    description: 'First time in top percentile',
    category: 'special',
    emoji: '🎯',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ topPercentile }) => (topPercentile ?? false),
  },
  {
    id: 'milestone_all_categories',
    label: 'Category Complete',
    description: 'Completed all categories at least once',
    category: 'special',
    emoji: '🌍',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ allCategories }) => (allCategories ?? false),
  },
  {
    id: 'milestone_pro_day',
    label: 'Pro Training',
    description: 'Trained the day after unlocking Pro',
    category: 'special',
    emoji: '💎',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ proDay }) => (proDay ?? false),
  },
  {
    id: 'milestone_referral',
    label: 'Friend Referrer',
    description: 'Referred a friend',
    category: 'special',
    emoji: '👥',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ referred }) => (referred ?? false),
  },
  {
    id: 'milestone_share',
    label: 'Results Sharer',
    description: 'Shared a result',
    category: 'special',
    emoji: '📤',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ shared }) => (shared ?? false),
  },
  {
    id: 'milestone_difficulty_change',
    label: 'Challenge Changer',
    description: 'Changed difficulty mid-week',
    category: 'special',
    emoji: '🔄',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ difficultyChange }) => (difficultyChange ?? false),
  },
  {
    id: 'milestone_perfect_week',
    label: 'Perfect Week',
    description: 'Completed a full week with zero skips',
    category: 'special',
    emoji: '✓',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ perfectWeek }) => (perfectWeek ?? false),
  },
  {
    id: 'milestone_anniversary',
    label: 'One Year Anniversary',
    description: 'One year anniversary on the app',
    category: 'special',
    emoji: '🎉',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ oneYearAnniversary }) => (oneYearAnniversary ?? false),
  },

  // ── Fun/Personality Badges (25) ────────────────────────────────────
  {
    id: 'fun_speed_demon',
    label: 'Speed Demon',
    description: '10 answers under 3 seconds in one session',
    category: 'fun',
    emoji: '🏃',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ speedDemon }) => (speedDemon ?? false),
  },
  {
    id: 'fun_perfectionist',
    label: 'The Perfectionist',
    description: '100% accuracy 3 sessions in a row',
    category: 'fun',
    emoji: '🎯',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ perfectionist }) => (perfectionist ?? false),
  },
  {
    id: 'fun_grinder',
    label: 'The Grinder',
    description: '5 sessions in one day',
    category: 'fun',
    emoji: '💪',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ grinder }) => (grinder ?? false),
  },
  {
    id: 'fun_comeback_kid',
    label: 'Comeback Kid',
    description: 'Return after 30 day absence',
    category: 'fun',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ comebackKid }) => (comebackKid ?? false),
  },
  {
    id: 'fun_consistent',
    label: 'The Consistent One',
    description: 'Consistency score above 90',
    category: 'fun',
    emoji: '📊',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ consistent }) => (consistent ?? false),
  },
  {
    id: 'fun_early_adopter',
    label: 'The Early Adopter',
    description: 'Joined in first month',
    category: 'fun',
    emoji: '🚀',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ earlyAdopter }) => (earlyAdopter ?? false),
  },
  {
    id: 'fun_night_shift',
    label: 'Night Shift',
    description: '10 sessions after midnight',
    category: 'fun',
    emoji: '🌙',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ nightShift }) => (nightShift ?? false),
  },
  {
    id: 'fun_mathematician',
    label: 'The Mathematician',
    description: '1000 correct math answers',
    category: 'fun',
    emoji: '🧮',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ mathematician }) => (mathematician ?? false),
  },
  {
    id: 'fun_iron_mind',
    label: 'Iron Mind',
    description: 'Complete a session with 0 correct and immediately retry',
    category: 'fun',
    emoji: '💎',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ ironMind }) => (ironMind ?? false),
  },
  {
    id: 'fun_challenger',
    label: 'The Challenger',
    description: 'Attempt hard mode within first 5 sessions',
    category: 'fun',
    emoji: '⚔️',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ challenger }) => (challenger ?? false),
  },
  {
    id: 'fun_speed_reader',
    label: 'Speed Reader',
    description: 'Average under 4 seconds for a full session',
    category: 'fun',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ speedReader }) => (speedReader ?? false),
  },
  {
    id: 'fun_no_mercy',
    label: 'No Mercy',
    description: 'Perfect score on hard mode',
    category: 'fun',
    emoji: '👑',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ noMercy }) => (noMercy ?? false),
  },
  {
    id: 'fun_machine',
    label: 'The Machine',
    description: '100 sessions total',
    category: 'fun',
    emoji: '🤖',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ totalDrills }) => totalDrills >= 100,
  },
  {
    id: 'fun_laser_focus',
    label: 'Laser Focus',
    description: 'Zero incorrect in 5-minute session',
    category: 'fun',
    emoji: '🎯',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ laserFocus }) => (laserFocus ?? false),
  },
  {
    id: 'fun_category_king',
    label: 'Category King',
    description: 'Master all 5 categories',
    category: 'fun',
    emoji: '👑',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ categoryKing }) => (categoryKing ?? false),
  },
  {
    id: 'fun_veteran',
    label: 'The Veteran',
    description: '1 year streak',
    category: 'fun',
    emoji: '🏅',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ streak }) => streak >= 365,
  },
  {
    id: 'fun_unstoppable',
    label: 'Unstoppable',
    description: '30-day streak twice',
    category: 'fun',
    emoji: '🚀',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ unstoppable }) => (unstoppable ?? false),
  },
  {
    id: 'fun_finisher',
    label: 'The Finisher',
    description: 'Complete every started session for 30 days',
    category: 'fun',
    emoji: '✓',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ finisher }) => (finisher ?? false),
  },
  {
    id: 'fun_double_down',
    label: 'Double Down',
    description: 'Two sessions in under 10 minutes',
    category: 'fun',
    emoji: '⚡',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ doubleDown }) => (doubleDown ?? false),
  },
  {
    id: 'fun_analyst',
    label: 'The Analyst',
    description: 'Check progress page 20 times',
    category: 'fun',
    emoji: '📊',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ analyticsViews20 }) => (analyticsViews20 ?? false),
  },
  {
    id: 'fun_clutch_player',
    label: 'Clutch Player',
    description: 'Improve score in last 3 questions',
    category: 'fun',
    emoji: '🏀',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ clutchPlayer }) => (clutchPlayer ?? false),
  },
  {
    id: 'fun_marathon_runner',
    label: 'Marathon Runner',
    description: 'Complete 10-minute session 50 times',
    category: 'fun',
    emoji: '🏃',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ marathon50 }) => (marathon50 ?? false),
  },
  {
    id: 'fun_specialist',
    label: 'The Specialist',
    description: '100 drills in one category in one week',
    category: 'fun',
    emoji: '🎯',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ specialist }) => (specialist ?? false),
  },
  {
    id: 'fun_perfect_week_80',
    label: 'Perfect Week',
    description: '7 days, all sessions above 80%',
    category: 'fun',
    emoji: '⭐',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ perfectWeek80 }) => (perfectWeek80 ?? false),
  },
  {
    id: 'fun_legend',
    label: 'Legend',
    description: '365-day streak',
    category: 'fun',
    emoji: '👑',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ streak }) => streak >= 365,
  },
  {
    id: 'fun_four_day_streak',
    label: 'Four Day Forge',
    description: 'Complete 4 consecutive days',
    category: 'fun',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ streak }) => streak >= 4,
  },
  {
    id: 'fun_first_hundred',
    label: 'Century Club',
    description: 'Score 100+ in a single session',
    category: 'fun',
    emoji: '💯',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ maxScore }) => maxScore >= 100,
  },
  {
    id: 'fun_recovery_expert',
    label: 'Recovery Expert',
    description: 'Improve score by 20+ points from previous session',
    category: 'fun',
    emoji: '📈',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ scoreRecovery20 }) => (scoreRecovery20 ?? false),
  },
  ];